name: Build and Release Binary

# Trigger on push to main branch and manual release creation
on:
  push:
    branches:
      - 'main'
  release:
    types:
      - published

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      # Build the binary
      - name: Build Binary
        run: |
          go build -o mondoo-webapp main.go
          mkdir -p artifacts
          mv mondoo-webapp ./artifacts/sidekick-${GITHUB_SHA}.zip

      # Tag the release (only on push to main)
      - name: Tag
        if: github.ref == 'refs/heads/main'
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          git tag "$TAG"
          git push origin "$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create the release and upload the binary (only on push to main or manual release)
      - name: Release
        if: github.ref == 'refs/heads/main' || github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.tag.outputs.TAG }}
          prerelease: false
          files: ./artifacts/sidekick-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
